framework:
    form:
        csrf_protection:
            token_id: submit

# Enable stateless CSRF protection for forms and logins/logouts
# csrf_protection:
#     stateless_token_ids:
#         - submit
#         - authenticate
#         - logout
